
# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  hello-world-laravel-postgres-data:
    driver: local    

services:
  # Postgres (9.6)
  mysql:
    image: ambientum/postgres:9.6
    container_name: hello-world-laravel-postgres
    volumes:
      - hello-world-laravel-postgres-data:/var/lib/mysql
    ports:
      - "5402:5432"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: hello-world-laravel-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
